name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: MUSICKIT_TOKEN=${{ secrets.MK_TOKEN}} npm run build

      - uses: lowply/deploy-firebase@v0.0.5
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: startrack-ng
          TARGET_BRANCH: main
